---
- name: Perform actions from inventory variables
  hosts: all
  pre_tasks:
    - name: Create a check mode flag if running in check mode
      ansible.builtin.file:
        path: "{{ check_flag }}"
        state: directory
      check_mode: false
      when: ansible_check_mode
    - name: Remove the check mode flag if not running in check mode
      ansible.builtin.file:
        path: "{{ check_flag }}"
        state: absent
      when: not ansible_check_mode
  tasks:
    - name: "Run call_mode='{{ call_mode }}', prop_type='{{ prop_type }}' upload"
      ansible.builtin.include_role:
        role: ansible-mega-var
        tasks_from: _download.yaml
      loop_control:
        loop_var: i
      loop: "{{ tests_meva[prop_type] }}"
      when:
        - call_mode == 'split'
        - prop_type != 'compress'

    - name: "Run call_mode='{{ call_mode }}', prop_type='{{ prop_type }}' upload"
      ansible.builtin.include_role:
        name: ansible-mega-var
      vars:
        meva_ghr2down: "{{ tests_meva[prop_type] }}"
      when:
        - call_mode == 'full'
        - prop_type != 'compress'

    - name: "Run call_mode='{{ call_mode }}', prop_type='{{ prop_type }}' compress"
      ansible.builtin.include_role:
        role: ansible-mega-var
        tasks_from: _download.yaml
      loop_control:
        loop_var: i
      loop: "{{ tests_compress if call_mode == 'remote' else (tests_compress |
        map('combine', {'delegate_to': 'localhost'})) }}" # DevSkim: ignore DS162092
      when: "prop_type == 'compress'"
