---
- name: Perform actions from inventory variables
  hosts: all
  pre_tasks:
    - name: Manage the check mode flag
      ansible.builtin.file:
        path: "{{ check_flag }}"
        state: "{{ 'directory' if ansible_check_mode else 'absent' }}"
        mode: "0755"
      check_mode: false
  tasks:
    - name: "Run call_mode='{{ call_mode }}', prop_type='{{ prop_type }}'
        upload" # noqa name[template]
      ansible.builtin.include_role:
        name: ansible-mega-var
        tasks_from: _download.yaml
      loop_control:
        loop_var: i
      loop: "{{ tests_meva[prop_type] }}"
      when:
        - call_mode == 'split'
        - prop_type != 'compress'

    - name: "Run call_mode='{{ call_mode }}', prop_type='{{ prop_type }}'
        upload" # noqa name[template]
      ansible.builtin.include_role:
        name: ansible-mega-var
      vars:
        meva_ghr2down: "{{ tests_meva[prop_type] }}"
      when:
        - call_mode == 'full'
        - prop_type != 'compress'

    - name: "Run call_mode='{{ call_mode }}', prop_type='{{ prop_type }}'
        compress" # noqa name[template]
      ansible.builtin.include_role:
        name: ansible-mega-var
        tasks_from: _download.yaml
      loop_control:
        loop_var: i
      loop: "{{ tests_compress if call_mode == 'remote' else (tests_compress |
        map('combine', {'delegate_to': 'localhost'})) }}" # DevSkim: ignore DS162092
      when: "prop_type == 'compress'"
