---
- name: Prepare targets
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for container to be ready
      ansible.builtin.raw: systemctl is-active basic.target
      register: _wait_result
      until: _wait_result.rc == 0
      retries: 33
      delay: 1
      changed_when: false
    - name: Remove downloads directory
      ansible.builtin.file:
        path: "{{ download_root }}"
        state: absent
    - name: Create downloads directory
      ansible.builtin.file:
        path: "{{ i.path }}"
        state: directory
        force: true
        recurse: true
      loop_control:
        loop_var: i
      loop: "{{ dirs2prepare }}"
      when: "prop_type.endswith('_other')"
