---
- name: Verify downloaded files
  hosts: all
  gather_facts: false
  tasks:
    - name: Converge run was in check_mode
      ansible.builtin.stat:
        path: "{{ check_flag }}"
      register: converge_check
    - name: Upload etalon output
      ansible.builtin.copy:
        src: >-
          {%- set dir = d_type -%}
          {%- if d_type == 'compress' -%}
            {%- if call_mode == 'full' -%}
              {%- set dir = 'local' -%}
            {%- else -%}
              {%- set dir = 'remote' -%}
            {%- endif -%}
          {%- endif -%}
          files/{{ dir }}/{{ file_name }}.txt
        dest: "/tmp/{{ file_name }}"
        force: true
        follow: false
        mode: "0644"
      loop_control:
        loop_var: file_name
      loop:
        - "01-check"
        - "02-converge"
        - "03-chevrge"
        - "04-update"
        - "05-u_check"
    - name: Get file list and hashes
      ansible.builtin.shell: |
        {%- set etalon = 'none' -%}
        {%- if ver2down == '000' -%}
          {%- if converge_check.stat.exists and post_dem is not defined -%}
            {%- set etalon = '01-check' -%}
          {%- elif not converge_check.stat.exists -%}
            {%- set etalon = '02-converge' -%}
          {%- elif converge_check.stat.exists and post_dem is defined -%}
            {%- set etalon = '03-chevrge' -%}
          {%- endif -%}
        {%- else -%}
          {%- if not converge_check.stat.exists -%}
            {%- set etalon = '04-update' -%}
          {%- elif converge_check.stat.exists -%}
            {%- set etalon = '05-u_check' -%}
          {%- endif -%}
        {%- endif -%}
        {
          find '{{ download_root }}' -type d -exec stat --format="%n %A %U %G" {} +
          find '{{ download_root }}' -type f -exec stat --format="%n %A %U %G %s" {} +
          find '{{ download_root }}' -type f -exec \
          md5sum {} + | sed -E 's/^([^ ]+)\s+(.+)$/\2 \1/' # DevSkim: ignore DS126858
        } | sort >/tmp/{{ etalon }}-{{ ctime }}
        awk '!/^[[:space:]]*$/ && !/^[[:space:]]*#/' /tmp/{{ etalon }} |
        sort >/tmp/{{ etalon }}.sorted
        diff -u /tmp/{{ etalon }}.sorted /tmp/{{ etalon }}-{{ ctime }} 2>&1
      register: files_info
      no_log: true
      check_mode: false
      changed_when: false
      ignore_errors: true
    - name: Assert non-zero rc
      ansible.builtin.assert:
        that: "files_info.rc == 0"
        fail_msg: "{{ files_info.stdout_lines | list }}"
