target-version = "py38"
indent-width = 2
line-length = 90

[lint]
preview = true
select = ["ALL"]
ignore = [
  "CPY", "D", # No copyrights and docs demands
  "E111",     # Indentation is not a multiple of 4
  "E114",     # Indentation is not a multiple of 4 (comment)
  "E402",     # Module level import not at top of file
]
fixable = ["ALL"]

[lint.flake8-quotes]
inline-quotes = "single"
docstring-quotes = "single"
multiline-quotes = "single"

[format]
quote-style = "single"
indent-style = "space"
