---
- name: Ensure some apt packages
  ansible.builtin.apt:
    name: "{{ i.name | default(omit) }}"
    update_cache: "{{ i.update_cache | default(omit) }}"
    state: "{{ i.state | default(omit) }}"
    autoclean: "{{ i.autoclean | default(omit) }}"
    autoremove: "{{ i.autoremove | default(omit) }}"
    cache_valid_time: "{{ i.cache_valid_time | default(omit) }}"
    deb: "{{ i.deb | default(omit) }}"
    default_release: "{{ i.default_release | default(omit) }}"
    dpkg_options: "{{ i.dpkg_options | default(omit) }}"
    force: "{{ i.force | default(omit) }}"
    install_recommends: "{{ i.install_recommends | default(omit) }}"
    only_upgrade: "{{ i.only_upgrade | default(omit) }}"
    pkg: "{{ i.pkg | default(omit) }}"
    policy_rc_d: "{{ i.policy_rc_d | default(omit) }}"
    purge: "{{ i.purge | default(omit) }}"
    allow_unauthenticated: "{{ i.allow_unauthenticated | default(omit) }}"
    allow_downgrade: "{{ i.allow_downgrade | default(omit) }}"
    lock_timeout: "{{ i.lock_timeout | default(omit) }}"
    force_apt_get: "{{ i.force_apt_get | default(omit) }}"
    clean: "{{ i.clean | default(omit) }}"
    upgrade: "{{ i.upgrade | default(omit) }}"
    update_cache_retries: "{{ i.update_cache_retries | default(omit) }}"
    update_cache_retry_max_delay: "{{ i.update_cache_retry_max_delay | default(omit) }}"
    allow_change_held_packages: "{{ i.allow_change_held_packages | default(omit) }}"
    fail_on_autoremove: "{{ i.fail_on_autoremove | default(omit) }}"
  when: ansible_pkg_mgr == 'apt'
  notify: "{{ i.notify | default(omit) }}"
  timeout: "{{ i.timeout | default(111) }}"
  retries: "{{ i.retries | default(3) }}"
  delay: "{{ i.delay | default(1) }}"
  until: _some_apt is success
  register: _some_apt
