---
- name: Upload some content
  ansible.builtin.copy:
    dest: "{{ i.dest | mandatory }}"
    content: "{{ i.content | mandatory }}"
    force: "{{ i.force | default(omit) }}"
    follow: "{{ i.follow | default(omit) }}"
    owner: "{{ i.owner | default(omit) }}"
    group: "{{ i.group | default(omit) }}"
    mode: "{{ i.mode | default('0644') }}"
  notify: "{{ i.notify | default(omit) }}"
