---
- name: Create some directories
  ansible.builtin.file:
    access_time: "{{ i.access_time | default(omit) }}"
    access_time_format: "{{ i.access_time_format | default(omit) }}"
    attributes: "{{ i.attributes | default(omit) }}"
    follow: "{{ i.follow | default(omit) }}"
    force: "{{ i.force | default(omit) }}"
    group: "{{ i.group | default(omit) }}"
    mode: "{{ i.mode | default('0755') }}"
    modification_time: "{{ i.modification_time | default(omit) }}"
    modification_time_format: "{{ i.modification_time_format | default(omit) }}"
    owner: "{{ i.owner | default(omit) }}"
    path: "{{ i.path | mandatory }}"
    recurse: "{{ i.recurse | default(omit) }}"
    selevel: "{{ i.selevel | default(omit) }}"
    serole: "{{ i.serole | default(omit) }}"
    setype: "{{ i.setype | default(omit) }}"
    src: "{{ i.src | default(omit) }}"
    state: "{{ i.state | default('directory') }}"
    unsafe_writes: "{{ i.unsafe_writes | default(omit) }}"
  notify: "{{ i.notify | default(omit) }}"
