---
- name: Set temporary name for download
  ansible.builtin.set_fact:
    _meva_down_name: >-
      /tmp/ansible-
      {%-
        set login =
          lookup('env', 'ANSIBLE_REMOTE_USER') |
          default(lookup('env', 'USER')) |
          default('file2down_login')
      -%}
      {%- if login | length > 0 -%}
      {{    login }}
      {%- else -%}
      {{    lookup('env', 'USER') }}
      {%- endif -%}-{{
        i.down_name |
        default(i.url) |
        default(i.creates) |
        regex_replace('[^a-z0-9\\.]', '_', ignorecase=True)
      }}
