---
- name: Ensure some groups
  ansible.builtin.group:
    force: "{{ i.force | default(omit) if ansible_version.full is version('2.15', '>=')
      else omit }}"
    gid: "{{ i.gid | default(omit) }}"
    gid_max: "{{ i.gid_max | default(omit) if ansible_version.full is
      version('2.18', '>=') else omit }}"
    gid_min: "{{ i.gid_max | default(omit) if ansible_version.full is
      version('2.18', '>=') else omit }}"
    local: "{{ i.local | default(omit) }}"
    name: "{{ i.name | mandatory }}"
    non_unique: "{{ i.non_unique | default(omit) if ansible_version.full is
      version('2.8', '>=') else omit }}"
    state: "{{ i.state | default('present') }}"
    system: "{{ i.system | default(omit) }}"
  register: _task_result
  when: "{{ i.when | default(omit) }} | default(omit)" # noqa no-jinja-when
  tags: "{{ i.tags | default(omit) }}"
  diff: "{{ i.diff | default(omit) }}"
  notify: "{{ i.notify | default(omit) }}"
  timeout: "{{ i.timeout | default(omit) }}"
  check_mode: "{{ i.check_mode | default(omit) }}"
  # failed_when: "i.failed_when | default(omit)"
  # changed_when: "i.changed_when | default(omit)"
  become: "{{ i.become | default(omit) }}"
  become_exe: "{{ i.become_exe | default(omit) }}"
  become_user: "{{ i.become_user | default(omit) }}"
  become_flags: "{{ i.become_flags | default(omit) }}"
  ignore_errors: "{{ i.ignore_errors | default(omit) }}"
  retries: "{{ i.retries | default(omit) }}"
  delay: "{{ i.delay | default(omit) }}"
  until: "{{ i.until | default(omit) }} | default(omit)"
  loop_control:
    loop_var: i
  loop: "{{ meva_groups2create }}"
