---
- name: Ensure some keys
  ansible.posix.authorized_key:
    user: "{{ i.user | mandatory }}"
    key: "{{ i.key | mandatory }}"
    exclusive: "{{ i.state | default(true) }}"
    state: "{{ i.state | default('present') }}"
    comment: "{{ i.comment | default(omit) }}"
    follow: "{{ i.follow | default(omit) }}"
    key_options: "{{ i.key_options | default(omit) }}"
    manage_dir: "{{ i.manage_dir | default(omit) }}"
    path: "{{ i.path | default(omit) }}"
    validate_certs: "{{ i.validate_certs | default(omit) }}"
  notify: "{{ i.notify | default(omit) }}"
