---
- name: Ensure some keys
  ansible.posix.authorized_key:
    comment: "{{ i.comment | default(omit) }}"
    exclusive: "{{ i.exclusive | default(omit) }}"
    follow: "{{ i.follow | default(omit) }}"
    key_options: "{{ i.key_options | default(omit) }}"
    key: "{{ i.key | mandatory }}"
    manage_dir: "{{ i.manage_dir | default(omit) }}"
    path: "{{ i.path | default(omit) }}"
    state: "{{ i.state | default('present') }}"
    user: "{{ i.user | mandatory }}"
    validate_certs: "{{ i.validate_certs | default(omit) }}"
  register: _task_result
  when: "{{ i.when | default(omit) }} | default(omit)" # noqa no-jinja-when
  tags: "{{ i.tags | default(omit) }}"
  diff: "{{ i.diff | default(omit) }}"
  notify: "{{ i.notify | default(omit) }}"
  timeout: "{{ i.timeout | default(omit) }}"
  check_mode: "{{ i.check_mode | default(omit) }}"
  # failed_when: "i.failed_when | default(omit)"
  # changed_when: "i.changed_when | default(omit)"
  become: "{{ i.become | default(omit) }}"
  become_exe: "{{ i.become_exe | default(omit) }}"
  become_user: "{{ i.become_user | default(omit) }}"
  become_flags: "{{ i.become_flags | default(omit) }}"
  ignore_errors: "{{ i.ignore_errors | default(omit) }}"
  retries: "{{ i.retries | default(omit) }}"
  delay: "{{ i.delay | default(omit) }}"
  until: "{{ i.until | default(omit) }} | default(omit)"
