---
- name: Ensure some volume groups
  community.general.lvg:
    force: "{{ i.force | default('no') }}"
    pesize: "{{ i.pesize | default(omit) }}"
    pv_options: "{{ i.pv_options | default(omit) }}"
    pvresize: "{{ i.pvresize | default(omit) }}"
    pvs: "{{ i.pvs | default(omit) }}"
    remove_extra_pvs: "{{ i.remove_extra_pvs | default(omit) }}"
    reset_pv_uuid: "{{ i.reset_pv_uuid | default(omit) }}"
    reset_vg_uuid: "{{ i.reset_vg_uuid | default(omit) }}"
    state: "{{ i.state | default(omit) }}"
    vg_options: "{{ i.vg_options | default(omit) }}"
    vg: "{{ i.vg | default(omit) }}"
  notify: "{{ i.notify | default(omit) }}"
