---
- name: Ensure some volume groups
  community.general.lvg:
    force: "{{ i.force | default('no') }}"
    pesize: "{{ i.pesize | default(omit) }}"
    pv_options: "{{ i.pv_options | default(omit) }}"
    pvresize: "{{ i.pvresize | default(omit) }}"
    pvs: "{{ i.pvs | default(omit) }}"
    remove_extra_pvs: "{{ i.remove_extra_pvs | default(omit) }}"
    reset_pv_uuid: "{{ i.reset_pv_uuid | default(omit) }}"
    reset_vg_uuid: "{{ i.reset_vg_uuid | default(omit) }}"
    state: "{{ i.state | default(omit) }}"
    vg_options: "{{ i.vg_options | default(omit) }}"
    vg: "{{ i.vg | default(omit) }}"
  register: _task_result
  when: "{{ i.when | default(omit) }} | default(omit)" # noqa no-jinja-when
  tags: "{{ i.tags | default(omit) }}"
  diff: "{{ i.diff | default(omit) }}"
  notify: "{{ i.notify | default(omit) }}"
  timeout: "{{ i.timeout | default(omit) }}"
  check_mode: "{{ i.check_mode | default(omit) }}"
  # failed_when: "i.failed_when | default(omit)"
  # changed_when: "i.changed_when | default(omit)"
  become: "{{ i.become | default(omit) }}"
  become_exe: "{{ i.become_exe | default(omit) }}"
  become_user: "{{ i.become_user | default(omit) }}"
  become_flags: "{{ i.become_flags | default(omit) }}"
  ignore_errors: "{{ i.ignore_errors | default(omit) }}"
  retries: "{{ i.retries | default(omit) }}"
  delay: "{{ i.delay | default(omit) }}"
  until: "{{ i.until | default(omit) }} | default(omit)"
  loop_control:
    loop_var: i
  loop: "{{ meva_lvg }}"
