---
- name: Ensure some logical volumes
  community.general.lvol:
    active: "{{ i.active | default(omit) }}"
    force: "{{ i.force | default('no') }}"
    lv: "{{ i.lv | default(omit) }}"
    opts: "{{ i.opts | default(omit) }}"
    pvs: "{{ i.pvs | default(omit) }}"
    resizefs: "{{ i.resizefs | default(omit) }}"
    shrink: "{{ i.shrink | default(omit) }}"
    size: "{{ i.size | default(omit) }}"
    snapshot: "{{ i.snapshot | default(omit) }}"
    state: "{{ i.state | default(omit) }}"
    thinpool: "{{ i.thinpool | default(omit) }}"
    vg: "{{ i.vg | default(omit) }}"
  register: _task_result
  when: "i.when | default(omit)"
  tags: "{{ i.tags | default(omit) }}"
  diff: "{{ i.diff | default(omit) }}"
  notify: "{{ i.notify | default(omit) }}"
  timeout: "{{ i.timeout | default(omit) }}"
  check_mode: "{{ i.check_mode | default(omit) }}"
  # failed_when: "i.failed_when | default(omit)"
  # changed_when: "i.changed_when | default(omit)"
  become: "{{ i.become | default(omit) }}"
  become_exe: "{{ i.become_exe | default(omit) }}"
  become_user: "{{ i.become_user | default(omit) }}"
  become_flags: "{{ i.become_flags | default(omit) }}"
  ignore_errors: "{{ i.ignore_errors | default(omit) }}"
  retries: "{{ i.retries | default(omit) }}"
  delay: "{{ i.delay | default(omit) }}"
  until: "i.until | default(omit)"
