---
- name: Rsync some files
  ansible.posix.synchronize:
    _local_rsync_password: "{{ i._local_rsync_password | default(omit) }}"
    _local_rsync_path: "{{ i._local_rsync_path | default(omit) }}"
    _ssh_args: "{{ i._ssh_args | default(omit) }}"
    _substitute_controller: "{{ i._substitute_controller | default(omit) }}"
    archive: "{{ i.archive | default(omit) }}"
    checksum: "{{ i.checksum | default(omit) }}"
    compress: "{{ i.compress | default(omit) }}"
    copy_links: "{{ i.copy_links | default(omit) }}"
    delay_updates: "{{ i.delay_updates | default(omit) }}"
    delete: "{{ i.delete | default(omit) }}"
    dest: "{{ i.dest | mandatory }}"
    dest_port: "{{ i.dest_port | mandatory }}"
    dirs: "{{ i.dirs | mandatory }}"
    existing_only: "{{ i.existing_only | mandatory }}"
    group: "{{ i.group | mandatory }}"
    link_dest: "{{ i.link_dest | mandatory }}"
    links: "{{ i.links | mandatory }}"
    mode: "{{ i.mode | mandatory }}"
    owner: "{{ i.owner | mandatory }}"
    partial: "{{ i.partial | mandatory }}"
    perms: "{{ i.perms | mandatory }}"
    private_key: "{{ i.private_key | mandatory }}"
    recursive: "{{ i.recursive | default(omit) }}"
    rsync_opts: "{{ i.rsync_opts | default(omit) }}"
    rsync_path: "{{ i.rsync_path | default(omit) }}"
    rsync_timeout: "{{ i.rsync_timeout | default(omit) }}"
    set_remote_user: "{{ i.set_remote_user | default(omit) }}"
    src: "{{ i.src | mandatory }}"
    ssh_connection_multiplexing: "{{ i.rsync_opts | default(omit) }}"
    times: "{{ i.rsync_opts | default(omit) }}"
    use_ssh_args: "{{ i.rsync_opts | default(omit) }}"
    verify_host: "{{ i.rsync_opts | default(omit) }}"
  notify: "{{ i.notify | default(omit) }}"
