---
- name: Rsync some files
  ansible.posix.synchronize:
    _local_rsync_password: "{{ i._local_rsync_password | default(omit) }}"
    _local_rsync_path: "{{ i._local_rsync_path | default(omit) }}"
    _ssh_args: "{{ i._ssh_args | default(omit) }}"
    _substitute_controller: "{{ i._substitute_controller | default(omit) }}"
    archive: "{{ i.archive | default(omit) }}"
    checksum: "{{ i.checksum | default(omit) }}"
    compress: "{{ i.compress | default(omit) }}"
    copy_links: "{{ i.copy_links | default(omit) }}"
    delay_updates: "{{ i.delay_updates | default(omit) }}"
    delete: "{{ i.delete | default(omit) }}"
    dest: "{{ i.dest | mandatory }}"
    dest_port: "{{ i.dest_port | default(omit) }}"
    dirs: "{{ i.dirs | default(omit) }}"
    existing_only: "{{ i.existing_only | default(omit) }}"
    group: "{{ i.group | default(omit) }}"
    link_dest: "{{ i.link_dest | default(omit) }}"
    links: "{{ i.links | default(omit) }}"
    mode: "{{ i.mode | default(omit) }}"
    owner: "{{ i.owner | default(omit) }}"
    partial: "{{ i.partial | default(omit) }}"
    perms: "{{ i.perms | default(omit) }}"
    private_key: "{{ i.private_key | default(omit) }}"
    recursive: "{{ i.recursive | default(omit) }}"
    rsync_opts: "{{ i.rsync_opts | default(omit) }}"
    rsync_path: "{{ i.rsync_path | default(omit) }}"
    rsync_timeout: "{{ i.rsync_timeout | default(omit) }}"
    set_remote_user: "{{ i.set_remote_user | default(omit) }}"
    src: "{{ i.src | mandatory }}"
    ssh_connection_multiplexing: "{{ i.rsync_opts | default(omit) }}"
    times: "{{ i.rsync_opts | default(omit) }}"
    use_ssh_args: "{{ i.rsync_opts | default(omit) }}"
    verify_host: "{{ i.rsync_opts | default(omit) }}"
  register: _task_result
  when: "{{ i.when | default(omit) }} | default(omit)" # noqa no-jinja-when
  tags: "{{ i.tags | default(omit) }}"
  diff: "{{ i.diff | default(omit) }}"
  notify: "{{ i.notify | default(omit) }}"
  timeout: "{{ i.timeout | default(omit) }}"
  check_mode: "{{ i.check_mode | default(omit) }}"
  # failed_when: "i.failed_when | default(omit)"
  # changed_when: "i.changed_when | default(omit)"
  become: "{{ i.become | default(omit) }}"
  become_exe: "{{ i.become_exe | default(omit) }}"
  become_user: "{{ i.become_user | default(omit) }}"
  become_flags: "{{ i.become_flags | default(omit) }}"
  ignore_errors: "{{ i.ignore_errors | default(omit) }}"
  retries: "{{ i.retries | default(omit) }}"
  delay: "{{ i.delay | default(omit) }}"
  until: "{{ i.until | default(omit) }} | default(omit)"
