---
- name: Launch some shell
  ansible.builtin.shell:
    chdir: "{{ i.chdir | default(omit) }}"
    cmd: "{{ i.cmd | default(omit) }}"
    creates: "{{ i.creates | default(omit) }}"
    executable: "{{ i.executable | default(omit) }}"
    free_form: "{{ i.free_form | default(omit) }}"
    removes: "{{ i.removes | default(omit) }}"
    stdin: "{{ i.stdin | default(omit) }}"
    stdin_add_newline: "{{ i.stdin_add_newline | default(omit) if ansible_version.full is
      version('2.8', '>=') else omit }}"
  register: _task_result
  when: "{{ i.when | default(omit) }} | default(omit)" # noqa no-jinja-when
  tags: "{{ i.tags | default(omit) }}"
  diff: "{{ i.diff | default(omit) }}"
  notify: "{{ i.notify | default(omit) }}"
  timeout: "{{ i.timeout | default(omit) }}"
  check_mode: "{{ i.check_mode | default(omit) }}"
  changed_when: "{{ i.changed_when | default(omit) }} | default(omit)"
  failed_when: "{{ i.failed_when | default(omit) }} | default(_task_result.rc != 0)"
  become: "{{ i.become | default(omit) }}"
  become_exe: "{{ i.become_exe | default(omit) }}"
  become_user: "{{ i.become_user | default(omit) }}"
  become_flags: "{{ i.become_flags | default(omit) }}"
  ignore_errors: "{{ i.ignore_errors | default(omit) }}"
  retries: "{{ i.retries | default(omit) }}"
  delay: "{{ i.delay | default(omit) }}"
  until: "{{ i.until | default(omit) }} | default(omit)"
