---
- name: Upload some templates
  ansible.builtin.template:
    src: "{{ i.src | mandatory }}"
    dest: "{{ i.dest | mandatory }}"
    force: "{{ i.force | default(omit) }}"
    follow: "{{ i.follow | default(omit) }}"
    owner: "{{ i.owner | default(omit) }}"
    group: "{{ i.group | default(omit) }}"
    mode: "{{ i.mode | default('0644') }}"
  vars:
    v: "{{ i.vars | default(omit) }}"
  diff: "{{ i.diff | default(omit) }}"
  notify: "{{ i.notify | default(omit) }}"
