---
- name: Upload some templates
  ansible.builtin.template:
    attributes: "{{ i.attributes | default(omit) }}"
    backup: "{{ i.backup | default(omit) }}"
    block_end_string: "{{ i.block_end_string | default(omit) }}"
    block_start_string: "{{ i.block_start_string | default(omit) }}"
    comment_end_string: "{{ i.follow | default(omit) }}"
    comment_start_string: "{{ i.comment_start_string | default(omit) }}"
    dest: "{{ i.dest | mandatory }}"
    follow: "{{ i.follow | default(omit) }}"
    force: "{{ i.force | default(omit) }}"
    group: "{{ i.group | default(omit) }}"
    lstrip_blocks: "{{ i.lstrip_blocks | default(omit) }}"
    mode: "{{ i.mode | default('0644') }}"
    newline_sequence: "{{ i.newline_sequence | default(omit) }}"
    output_encoding: "{{ i.output_encoding | default(omit) }}"
    owner: "{{ i.owner | default(omit) }}"
    selevel: "{{ i.selevel | default(omit) }}"
    serole: "{{ i.serole | default(omit) }}"
    setype: "{{ i.setype | default(omit) }}"
    seuser: "{{ i.seuser | default(omit) }}"
    src: "{{ i.src | mandatory }}"
    trim_blocks: "{{ i.trim_blocks | default(omit) }}"
    unsafe_writes: "{{ i.unsafe_writes | default(omit) }}"
    validate: "{{ i.validate | default(omit) }}"
    variable_end_string: "{{ i.variable_end_string | default(omit) }}"
    variable_start_string: "{{ i.variable_start_string | default(omit) }}"
  vars:
    v: "{{ i.vars | default(omit) }}"
  diff: "{{ i.diff | default(omit) }}"
  notify: "{{ i.notify | default(omit) }}"
