# kics-scan disable=59029ddf-e651-412b-ae7b-ff6d403184bc
---
- name: Ensure some users
  ansible.builtin.user:
    append: "{{ i.append | default(omit) }}"
    authorization: "{{ i.authorization | default(omit) if ansible_version.full is
      version('2.8', '>=') else omit }}"
    comment: "{{ i.comment | default(omit) }}"
    create_home: "{{ i.create_home | default('no') }}"
    expires: "{{ i.expires | default(omit) }}"
    force: "{{ i.force | default(omit) }}"
    generate_ssh_key: "{{ i.generate_ssh_key | default(omit) }}"
    group: "{{ i.group | default(i.name) | default(omit) }}"
    groups: "{{ i.groups | default(omit) }}"
    hidden: "{{ i.hidden | default(omit) }}"
    home: "{{ i.home | default(omit) }}"
    local: "{{ i.local | default(omit) }}"
    login_class: "{{ i.login_class | default(omit) }}"
    move_home: "{{ i.move_home | default(omit) }}"
    name: "{{ i.name | mandatory }}"
    non_unique: "{{ i.non_unique | default(omit) }}"
    password_expire_account_disable: "{{ i.password_expire_account_disable |
      default(omit) if ansible_version.full is version('2.18', '>=') else omit }}"
    password_expire_max: "{{ i.password_expire_max | default(omit) if
      ansible_version.full is version('2.11', '>=') else omit }}"
    password_expire_min: "{{ i.password_expire_min | default(omit) if
      ansible_version.full is version('2.11', '>=') else omit }}"
    password_expire_warn: "{{ i.password_expire_warn | default(omit) if
      ansible_version.full is version('2.16', '>=') else omit }}"
    password_lock: "{{ i.password_lock | default(omit) }}"
    password: "{{ i.password | default(omit) }}"
    profile: "{{ i.profile | default(omit) if ansible_version.full is
      version('2.8', '>=') else omit }}"
    remove: "{{ i.remove | default(omit) }}"
    role: "{{ i.role | default(omit) if ansible_version.full is version('2.8', '>=')
      else omit }}"
    seuser: "{{ i.seuser | default(omit) }}"
    shell: "{{ i.shell | default(omit) }}"
    skeleton: "{{ i.skeleton | default(omit) }}"
    ssh_key_bits: "{{ i.ssh_key_bits | default(omit) }}"
    ssh_key_comment: "{{ i.ssh_key_comment | default(omit) }}"
    ssh_key_file: "{{ i.ssh_key_file | default(omit) }}"
    ssh_key_passphrase: "{{ i.ssh_key_passphrase | default(omit) }}"
    ssh_key_type: "{{ i.ssh_key_type | default(omit) }}"
    state: "{{ i.state | default('present') }}"
    system: "{{ i.system | default(omit) }}"
    uid_max: "{{ i.uid_max | default(omit) if ansible_version.full is
      version('2.18', '>=') else omit }}"
    uid_min: "{{ i.uid_min | default(omit) if ansible_version.full is
      version('2.18', '>=') else omit }}"
    uid: "{{ i.uid | default(omit) }}"
    umask: "{{ i.umask | default(omit) if ansible_version.full is
      version('2.12', '>=') else omit }}"
    update_password: "{{ i.update_password | default(omit) }}"
  register: _task_result
  when: "{{ i.when | default(omit) }} | default(omit)" # noqa no-jinja-when
  tags: "{{ i.tags | default(omit) }}"
  diff: "{{ i.diff | default(omit) }}"
  notify: "{{ i.notify | default(omit) }}"
  timeout: "{{ i.timeout | default(omit) }}"
  check_mode: "{{ i.check_mode | default(omit) }}"
  # failed_when: "i.failed_when | default(omit)"
  # changed_when: "i.changed_when | default(omit)"
  become: "{{ i.become | default(omit) }}"
  become_exe: "{{ i.become_exe | default(omit) }}"
  become_user: "{{ i.become_user | default(omit) }}"
  become_flags: "{{ i.become_flags | default(omit) }}"
  ignore_errors: "{{ i.ignore_errors | default(omit) }}"
  retries: "{{ i.retries | default(omit) }}"
  delay: "{{ i.delay | default(omit) }}"
  until: "{{ i.until | default(omit) }} | default(omit)"
