---
- name: Include settings temporary name for download
  ansible.builtin.include_tasks: down_name.yaml

# following two blocks due default(omit) work incorrect for delegate_to
# issue link: https://github.com/ansible/ansible/issues/14130
- name: Delegate_to value defined
  when: "'delegate_to' in i"
  block:
    - name: "Download to local url {{ i.url }}"
      become: false
      ansible.builtin.get_url:
        attributes: "{{ i.attributes | default(omit) }}"
        client_cert: "{{ i.client_cert | default(omit) }}"
        client_key: "{{ i.client_key | default(omit) }}"
        mode: "{{ i.down_mode | default('0644') }}"
        owner: "{{ i.down_owner | default(omit) }}"
        group: "{{ i.down_owner | default(omit) }}"
        timeout: "{{ i.timeout | default(omit) }}"
        dest: "{{ _meva_down_name }}"
        headers: "{{ i.headers | default(omit) }}"
        url: "{{ i.url | default(mandatory) }}"
        unredirected_headers: "{{ i.unredirected_headers | default(omit) }}"
        force: "{{ i.force | default(omit) }}"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      delegate_to: "{{ i.delegate_to }}"
      check_mode: false
      notify: "{{ i.notify | default(omit) }}"
    - name: Unpack downloaded archive and propagate files
      ansible.builtin.include_tasks: unp4pro.yaml

- name: Delegate_to value undefined
  when: "'delegate_to' not in i"
  block:
    - name: Download to remote url {{ i.url }}
      become: true
      ansible.builtin.get_url:
        attributes: "{{ i.attributes | default(omit) }}"
        client_cert: "{{ i.client_cert | default(omit) }}"
        client_key: "{{ i.client_key | default(omit) }}"
        mode: "{{ i.down_mode | default('0644') }}"
        owner: "{{ i.down_owner | default(omit) }}"
        group: "{{ i.down_owner | default(omit) }}"
        timeout: "{{ i.timeout | default(omit) }}"
        dest: "{{ _meva_down_name }}"
        headers: "{{ i.headers | default(omit) }}"
        url: "{{ i.url | default(mandatory) }}"
        unredirected_headers: "{{ i.unredirected_headers | default(omit) }}"
        # For 'force' parameter Ansible have bug
        # https://github.com/ansible/ansible/issues/64016
        force: "{{ i.force | default(omit) }}"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      notify: "{{ i.notify | default(omit) }}"
      check_mode: false
    - name: Unpack downloaded archive to destination
      ansible.builtin.include_tasks: unp2loc.yaml
