---
- name: include settings temporary name for download
  include_tasks: down_name.yaml

# following two blocks due default(omit) work incorrect for delegate_to
# issue link: https://github.com/ansible/ansible/issues/14130
- name: delegate_to value defined
  block:
    - name: "download url [{{ i.url }}] to local"
      become: false
      get_url:
        attributes: "{{ i.attributes | default(omit) }}"
        client_cert: "{{ i.client_cert | default(omit) }}"
        client_key: "{{ i.client_key | default(omit) }}"
        mode: "{{ i.down_mode | default('0644') }}"
        owner: "{{ i.down_owner | default(omit) }}"
        group: "{{ i.down_owner | default(omit) }}"
        timeout: "{{ i.timeout | default(omit) }}"
        dest: "{{ _meva_down_name }}"
        headers: "{{ i.headers | default(omit) }}"
        url: "{{ i.url | default(mandatory) }}"
        unredirected_headers: "{{ i.unredirected_headers | default(omit) }}"
        force: "{{ i.force | default(omit) }}"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      delegate_to: "{{ i.delegate_to }}"
      check_mode: false
      notify: "{{ i.notify | default(omit) }}"
    - name: unpack downloaded archive and propagate files
      include_tasks: unp4pro.yaml
  when: "'delegate_to' in i"

- name: delegate_to value undefined
  block:
    - name: "download url [{{ i.url }}] to remote"
      become: true
      get_url:
        attributes: "{{ i.attributes | default(omit) }}"
        client_cert: "{{ i.client_cert | default(omit) }}"
        client_key: "{{ i.client_key | default(omit) }}"
        mode: "{{ i.down_mode | default('0644') }}"
        owner: "{{ i.down_owner | default(omit) }}"
        group: "{{ i.down_owner | default(omit) }}"
        timeout: "{{ i.timeout | default(omit) }}"
        dest: "{{ _meva_down_name }}"
        headers: "{{ i.headers | default(omit) }}"
        url: "{{ i.url | default(mandatory) }}"
        unredirected_headers: "{{ i.unredirected_headers | default(omit) }}"
        # For 'force' parameter Ansible have bug
        # https://github.com/ansible/ansible/issues/64016
        force: "{{ i.force | default(omit) }}"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      notify: "{{ i.notify | default(omit) }}"
      check_mode: false
    - name: unpack downloaded archive to destination
      include_tasks: unp2loc.yaml
  when:
    - "'delegate_to' not in i"
