---
- name: Ensure some packages
  ansible.builtin.include_tasks: _apt.yaml

- name: Ensure some groups
  ansible.builtin.include_tasks: _group.yaml

- name: Ensure some users
  ansible.builtin.include_tasks: _user.yaml

- name: Ensure some files or directories
  ansible.builtin.include_tasks: _file.yaml

- name: Upload some templates
  ansible.builtin.include_tasks: _template.yaml

- name: Copy some files
  ansible.builtin.include_tasks: _copy.yaml

- name: Rsync some files
  ansible.builtin.include_tasks: _rsync.yaml

- name: Create some systemd units
  ansible.builtin.include_tasks: _systemd.yaml

- name: Ensure some keys
  ansible.builtin.include_tasks: _key.yaml

- name: Download some files
  ansible.builtin.include_tasks: _download.yaml
  loop_control:
    loop_var: i
  loop: "{{ meva_file2down | default([]) + meva_ghr2down | default([]) }}"

- name: Partitioning some disks
  ansible.builtin.include_tasks: _parted.yaml

- name: Ensure some volume groups
  ansible.builtin.include_tasks: _lvg.yaml

- name: Ensure some logical volumes
  ansible.builtin.include_tasks: _lvol.yaml

- name: Ensure some file systems
  ansible.builtin.include_tasks: _filesystem.yaml

- name: Ensure some file mounts
  ansible.builtin.include_tasks: _mount.yaml

- name: Command to run
  ansible.builtin.include_tasks: _command.yaml

- name: Run for shell
  ansible.builtin.include_tasks: _shell.yaml
