---
meva_arch_map1:
  i386: "i386"
  x86_64: "amd64"
  aarch64: "arm64"
  armv7l: "arm"
meva_arch_bin1: >-
  {{
    meva_arch_map1[ansible_architecture] |
    default(ansible_architecture)
  }}
ctime: "{{ now(fmt='%Y%m%d%H%M%S') }}"
github_token: "{{ lookup('env', 'ANSIBLE_GITHUB_TOKEN') }}"
prop_type: "{{ lookup('ansible.builtin.env', 'ANSIBLE_PROP_TYPE',
  default='simple_target') }}"
call_mode: "{{ lookup('ansible.builtin.env', 'ANSIBLE_CALL_MODE', default='split') }}"
gh_owner: raven428
check_flag: "{{ download_root }}/to-notify-verifier-that-converged-in-check-mode"
ver2down: >-
  {{ lookup('ansible.builtin.env', 'ANSIBLE_DOWNLOAD_TAG', default='000') }}
download_tag: "v{{ ver2down }}"
download_root: "/tmp/molecule"
download_topic: "pyenv-emtpy"
download_version_file: "2.2.4"
download_file_name: >-
  {{ download_topic }}-{{
    download_version_file |
    regex_replace('[^0-9a-z]', '_', ignorecase=True)
  }}-linux-{{
    meva_arch_bin1
  }}.tar.xz
decompressed_file_name: "decompressed-file-name"
download_files:
  simple_uri: >-
    https://github.com/raven428/finch-externaleditor/releases/download/{{
      download_tag
    }}/{{
      download_file_name
    }}
github_repo_pub: "finch-externaleditor"
github_repo_priv: "far-smartpad"
github_repo_owner: "raven428"
default_time: "201111111111.11"
download_types:
  simple: "simple"
  release: "release"
download_paths:
  single: "single"
  compress: "compress"
  arch_full: "arch-full"
  arch_tree: "arch-tree"
download_options:
  direct: "direct-download"
  con_copy: "controller-copy"
  con_rsync: "controller-rsync"
dirs2prepare: |
  {%- set result = [ ] -%}
  {%- for path in download_paths.values() -%}
    {%- for option in download_options.values() -%}
      {%- do result.append({'path': download_root ~ '/' ~ path ~ '/' ~ option}) -%}
    {%- endfor -%}
  {%- endfor -%}
  {{  result | list }}
meva_packages:
  - name:
      - xz-utils
    update_cache: true

# for 1.4.*
meva_pickup_files:
  # 0.0.0 result = /i.dest/Makefile
  - name: "pyenv/Makefile"
    file_mode: "0640"
  # 0.0.1 result = /i.dest/f.dest-dir/Makefile
  - name: "pyenv/Makefile"
    dest: "f.dest-dir1/"
    exec_mode: "0641"
    file_mode: "0641"
  # 0.0.2 result = /i.dest/f.dest-dir/Makefile-in-f.dest
  - name: "pyenv/Makefile"
    dest: "f.dest-dir2/in-f.dest-Makefile"
    file_mode: "0642"
  # 0.1.0 result = /f.dest/Makefile
  - name: "pyenv/Makefile"
    dest: "{{ download_root }}/f.dest-abs1/"
    file_mode: "0640"
  # 0.1.1 result = f.dest
  - name: "pyenv/pyenv.d/rehash/conda.d/default.list"
    dest: "{{ download_root }}/f.dest-abs2/file-default.list"
    file_mode: "0640"
  # 0.2.0/0.0.0 result = /i.dest/pyenv
  - name: "pyenv/bin/"
    file_mode: "0755"
  # 0.2.0/0.0.1 result = /i.dest/relative-f.dest-trailing-slash-yes/
  - name: "pyenv/bin/"
    dest: "relative-f.dest-trailing-slash-yes/"
    dir_mode: "0543"
    exec_mode: "0755"
    file_mode: "0755"
  # 0.2.0/0.0.2 result = /i.dest/relative-f.dest-trailing-slash-no/
  - name: "pyenv/bin/"
    dest: "relative-f.dest-trailing-slash-no"
    dir_mode: "0643"
    exec_mode: "0755"
    file_mode: "0755"
  # 0.2.0/0.1.0 result = /i.dest/absolute-f.dest-trailing-slash-yes/pyenv
  - name: "pyenv/bin/"
    dest: "{{ download_root }}/absolute-f.dest-trailing-slash-yes/"
    file_mode: "0755"
  # 0.2.0/0.1.1 result = /i.dest/absolute-f.dest-trailing-slash-no/pyenv
  - name: "pyenv/bin/"
    dest: "{{ download_root }}/absolute-f.dest-trailing-slash-no"
    dir_mode: "0752"
    exec_mode: "0755"
    file_mode: "0755"
  # 0.2.1/0.0.0 result = /i.dest/install
  - name: "pyenv/pyenv.d/install"
    file_mode: "0755"
  # 0.2.1/0.0.1 result = /i.dest/relative-f.dest-trailing-yes/bin/pyenv
  - name: "pyenv/bin"
    dest: "relative-f.dest-trailing-yes/"
    exec_mode: "0755"
    file_mode: "0755"
  # 0.2.1/0.0.2 result = /i.dest/relative-f.dest-trailing-no/bin/pyenv
  - name: "pyenv/bin"
    dest: "relative-f.dest-trailing-no"
    dir_mode: "0743"
    exec_mode: "0755"
    file_mode: "0755"
  # 0.2.1/0.1.0 result = /i.dest/absolute-f.dest-trailing-yes/bin/pyenv
  - name: "pyenv/bin"
    dest: "{{ download_root }}/absolute-f.dest-trailing-yes/"
    dir_mode: "0731"
    exec_mode: "0731"
    file_mode: "0731"
  # 0.2.1/0.1.1 result = /i.dest/absolute-f.dest-trailing-no/bin/pyenv
  - name: "pyenv/bin"
    dest: "{{ download_root }}/absolute-f.dest-no"
    dir_mode: "0731"
    exec_mode: "0755"
    file_mode: "0755"

meva_other_files:
  # x. -"-
  #   1. single raw
  #     1. directly to target host
  - dest: "{{ download_root }}/{{ download_paths.single }}/{{
      download_options.direct }}"
    down_name: "{{ download_paths.single }}-{{ download_options.direct }}.xz"
    creates: "{{ download_file_name }}"
    down_mode: "0641"
    exec_bit: "0000"
    modification_time: "{{ default_time }}"
  # x. -"-
  #   1. single raw
  #     2. at the Ansible controller with `copy:`
  - dest: "{{ download_root }}/{{ download_paths.single }}/{{
      download_options.con_copy }}"
    down_name: "{{ download_paths.single }}-{{ download_options.con_copy }}.xz"
    creates: "{{ download_file_name }}"
    down_mode: "0641"
    exec_bit: "0000"
    modification_time: "{{ default_time }}"
    delegate_to: localhost # DevSkim: ignore DS162092
  # x. -"-
  #   2. single compressed
  #     1. directly to target host
  - dest: "{{ download_root }}/{{ download_paths.compress }}/{{
      download_options.direct }}"
    down_name: "{{ download_paths.compress }}-{{ download_options.direct }}.xz"
    creates: "{{ decompressed_file_name }}"
    down_mode: "0641"
    exec_bit: "0000"
    modification_time: "{{ default_time }}"
    archive: true
    files: []
  # x. -"-
  #   2. single compressed
  #     2. at the Ansible controller with `copy:`
  - dest: "{{ download_root }}/{{ download_paths.compress }}/{{
      download_options.con_copy }}"
    down_name: "{{ download_paths.compress }}-{{ download_options.con_copy }}.xz"
    # file name to decompress:
    creates: "{{ decompressed_file_name }}"
    delegate_to: localhost # DevSkim: ignore DS162092
    down_mode: "0642"
    modification_time: "{{ default_time }}"
    archive: true
    files: []
  # x. -"-
  #   3. archive with directory tree
  #     1. directly to target host
  - dest: "{{ download_root }}/{{ download_paths.arch_full }}/{{
      download_options.direct }}"
    down_name: "{{ download_paths.arch_full }}-{{ download_options.direct }}-{{
      ver2down }}.tar.xz"
    creates: "pyenv/build-{{ ver2down }}"
    dir_mode: "0750"
    exec_mode: "0705"
    file_mode: "0604"
    modification_time: "{{ default_time }}"
    archive: true
  # x. -"-
  #   3. archive with directory tree
  #     2. at the Ansible controller with `unarchive:`
  - dest: "{{ download_root }}/{{ download_paths.arch_full }}/{{
      download_options.con_copy }}"
    down_name: "{{ download_paths.arch_full }}-{{ download_options.con_copy }}-
      {{ ver2down }}.tar.xz"
    creates: "pyenv/build-{{ ver2down }}"
    delegate_to: localhost # DevSkim: ignore DS162092
    dir_mode: "0751"
    exec_mode: "0703"
    file_mode: "0602"
    modification_time: "{{ default_time }}"
    archive: true

meva_release_addon:
  gh_tag: "{{ download_tag }}"
  gh_repo: "{{ github_repo_pub }}"
  gh_owner: "{{ github_repo_owner }}"
  gh_token: "{{ github_token }}"
  substring: "{{ download_file_name }}"

tests_meva:
  # 1.1.1 – 1.3.2 simple HTTPS connection by URI
  simple_other: "{{ meva_other_files | map('combine', {'url':
    download_files.simple_uri}) }}"

  # 1. simple HTTPS connection by URI
  #   4. archive with directory tree
  #     1. directly to target host
  simple_target:
    - url: "{{ download_files.simple_uri }}"
      down_name: "{{ download_options.direct }}-{{ ver2down }}.tar.xz"
      creates: "pyenv/build-{{ ver2down }}"
      dest: "{{ download_root }}"
      archive: true
      files: "{{ meva_pickup_files | list }}"

  # 1. simple HTTPS connection by URI
  #   4. archive with directory tree
  #     2. at the Ansible controller with `copy:`
  simple_controller:
    - url: "{{ download_files.simple_uri }}"
      down_name: "{{ download_options.con_copy }}-{{ ver2down }}.tar.xz"
      creates: "pyenv/build-{{ ver2down }}"
      dest: "{{ download_root }}"
      delegate_to: localhost # DevSkim: ignore DS162092
      archive: true
      files: "{{ meva_pickup_files | list }}"

  # 2.1.1 – 2.3.2 release from GitHub
  release_other: "{{ meva_other_files | map('combine', meva_release_addon) }}"

  # 2. release from GitHub
  #   4. archive with directory tree
  #     1. directly to target host
  release_target:
    - gh_tag: "{{ download_tag }}"
      gh_repo: "{{ github_repo_pub }}"
      gh_owner: "{{ github_repo_owner }}"
      gh_token: "{{ github_token }}"
      substring: "{{ download_file_name }}"
      down_name: "{{ download_options.direct }}-{{ ver2down }}.tar.xz"
      creates: "pyenv/build-{{ ver2down }}"
      dest: "{{ download_root }}"
      archive: true
      files: "{{ meva_pickup_files | list }}"

  # 2. release from GitHub
  #   4. archive with directory tree
  #     2. at the Ansible controller with `copy:`
  release_controller:
    - gh_tag: "{{ download_tag }}"
      gh_repo: "{{ github_repo_pub }}"
      gh_owner: "{{ github_repo_owner }}"
      gh_token: "{{ github_token }}"
      substring: "{{ download_file_name }}"
      down_name: "{{ download_options.con_copy }}-{{ ver2down }}.tar.xz"
      creates: "pyenv/build-{{ ver2down }}"
      dest: "{{ download_root }}"
      delegate_to: localhost # DevSkim: ignore DS162092
      archive: true
      files: "{{ meva_pickup_files | list }}"

compression_formats:
  - [gz, bz2, lz4]
  - [zst, lzma, xz]
download_prefix: >-
  https://github.com/raven428/finch-externaleditor/releases/download/{{
    download_tag
  }}/pyenv2decompress-2_2_4-linux-amd64.tar
tests_compress: >-
  {%- set result = [] -%}
  {%- for format in compression_formats | flatten -%}
    {%- do result.append({
      'url': download_prefix ~ '.' ~ format,
      'dest': download_root ~ '/' ~ format,
      'down_name': decompressed_file_name ~ '.' ~ format,
      'creates': decompressed_file_name,
      'archive': 'true',
      'down_mode': '0641',
      'exec_bit': '0000',
      'modification_time': default_time,
      'files': [],
    }) -%}
  {%- endfor -%}
  {{ result }}
