---
- name: Perform actions from inventory variables
  hosts: all
  pre_tasks:
    - name: Create a check mode flag if running in check mode
      ansible.builtin.file:
        path: "{{ check_flag }}"
        state: directory
      check_mode: false
      when: ansible_check_mode
    - name: Remove the check mode flag if not running in check mode
      ansible.builtin.file:
        path: "{{ check_flag }}"
        state: absent
      when: not ansible_check_mode
  tasks:
    - name: Run full role
      include_role:
        name: ansible-mega-var
      when: lookup('env', 'ANSIBLE_CALL_MODE') == 'full'
    - name: Run ghr2down part
      include_role:
        role: ansible-mega-var
        tasks_from: _ghr2down.yaml
      loop_control:
        loop_var: i
      loop: "{{ meva_ghr2down }}"
      when: lookup('env', 'ANSIBLE_CALL_MODE') == 'split'
    - name: Run file2down part
      include_role:
        name: ansible-mega-var
        tasks_from: _file2down.yaml
      loop_control:
        loop_var: i
      loop: "{{ meva_file2down }}"
      when: lookup('env', 'ANSIBLE_CALL_MODE') == 'split'
