---
name: test role
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "11 11 * * 1"
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  test-role:
    name: test role
    timeout-minutes: 33
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        image_name:
          - ansible-6_7_0:latest
          - ansible-9_9_0:latest
          - ansible-11_1_0:latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: test role
        env:
          IMAGE_NAME: ${{ matrix.image_name }}
          ANSIBLE_GITHUB_TOKEN: ${{ secrets.LOCAL_WS_TOKEN }}
        run: molecule/run-tests.sh
  linters:
    name: linters
    timeout-minutes: 11
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: lint the repo
        env:
          BRA: master
        run: |
          curl -sL \
          https://raw.githubusercontent.com/raven428/container-images/${{ env.none
          }}refs/heads/${{ env.BRA }}/sources/linters-ubuntu-22_04/check-dir.sh |
          bash
          curl -sL \
          https://raw.githubusercontent.com/raven428/container-images/${{ env.none
          }}refs/heads/${{ env.BRA }}/sources/ansible-ubuntu/check-dir.sh |
          bash
  MegaLinter:
    name: MegaLinter
    timeout-minutes: 11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: MegaLinter
        uses: oxsecurity/megalinter@v8
        env:
          VALIDATE_ALL_CODEBASE: true
