# kics-scan disable=555ab8f9-2001-455e-a077-f2d0f41e2fb9
---
name: test role
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "11 11 * * 1"
  # checkov:skip=CKV_GHA_7
  workflow_dispatch:
    inputs:
      mega_var_ref:
        description: "ansible-mega-var branch/tag to test against"
        required: false
        default: ""
      mini_vault_ref:
        description: "ansible-mini-vault branch/tag/SHA to test against"
        required: false
        default: ""
      mega_launch_ref:
        description: "ansible-launch-var branch/tag to test against"
        required: false
        default: ""
      mega_service_ref:
        description: "ansible-mega-service branch/tag/SHA to test against"
        required: false
        default: ""
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  default:
    name: default
    timeout-minutes: 33
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        call_mode:
          - full
          - split
        ansible_ver:
          - "06"
          - "07"
          - "08"
          - "09"
          - "10"
          - "11"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true
      - name: test role
        env:
          ANSIBLE_CALL_MODE: ${{ matrix.call_mode }}
          APPIMAGE_NAME: "ansible-${{ matrix.ansible_ver }}-001.AppImage"
          ANSIBLE_GITHUB_TOKEN: ${{ secrets.LOCAL_WS_TOKEN }}
        run: molecule/default/run-tests.sh
  downloads:
    name: t
    timeout-minutes: 33
    runs-on: ubuntu-24.04
    needs:
      - pytest
    strategy:
      fail-fast: false
      matrix:
        prop_type:
          - simple_other
          - simple_target
          - simple_controller
          - release_other
          - release_target
          - release_controller
          - compress # (full=remote, split=local)
        call_mode:
          - full
          - split
        ansible_ver:
          - "07"
          - "09"
          - "11"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true
      - name: test role
        env:
          ANSIBLE_PROP_TYPE: ${{ matrix.prop_type }}
          ANSIBLE_CALL_MODE: ${{ matrix.call_mode }}
          APPIMAGE_NAME: "ansible-${{ matrix.ansible_ver }}-001.AppImage"
          ANSIBLE_GITHUB_TOKEN: ${{ secrets.LOCAL_WS_TOKEN }}
        run: molecule/downloads/run-tests.sh
  pytest:
    name: Python tests
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true
      - name: run tests
        env:
          ANSIBLE_GITHUB_TOKEN: ${{ secrets.LOCAL_WS_TOKEN }}
        run: tests/run-tests.sh
  linters:
    name: linters
    timeout-minutes: 11
    runs-on: ubuntu-24.04
    if: github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true
      - name: lint the repo
        env:
          BRA: master
        run: |
          curl -sL \
          https://raw.githubusercontent.com/raven428/container-images/refs/heads/${{
          env.BRA }}/sources/linters-ubuntu-22_04/check-dir.sh | bash
          curl -sL \
          https://raw.githubusercontent.com/raven428/container-images/refs/heads/${{
          env.BRA }}/sources/ansible-ubuntu/check-dir.sh | bash
  MegaLinter:
    name: MegaLinter
    timeout-minutes: 11
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true
      - name: MegaLinter
        uses: oxsecurity/megalinter@v9
        env:
          VALIDATE_ALL_CODEBASE: true
  mega_service:
    name: test mega-service role
    timeout-minutes: 55
    runs-on: ubuntu-latest
    needs:
      - default
      - downloads
      - linters
      - MegaLinter
    if: github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    steps:
      - name: trigger and wait for mega-service workflow
        env:
          GH_TOKEN: ${{ secrets.LOCAL_WS_TOKEN }}
          MEGA_VAR_REF: ${{ github.head_ref || github.ref_name }}
          MINI_VAULT_REF: ${{ inputs.mini_vault_ref || 'master' }}
          MEGA_LAUNCH_REF: ${{ inputs.mega_launch_ref || 'master' }}
          MEGA_SERVICE_REF: ${{ inputs.mega_service_ref || 'master' }}
        run: 'gh workflow run test-role.yaml --repo raven428/ansible-mega-service --ref
          "${MEGA_SERVICE_REF}" --field mega_launch_ref="${MEGA_LAUNCH_REF}" --field
          mega_var_ref="${MEGA_VAR_REF}" --field mini_vault_ref="${MINI_VAULT_REF}"'
  all-green:
    name: all green
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: mega_service
    if: github.event_name == 'pull_request'
    permissions:
      checks: read
    steps:
      - name: waiting for checks success
        uses: poseidon/wait-for-status-checks@v0.6.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ignore: all green, foobar
          timeout: 111s
