---
default_time: "201111111111.11"
ctime: "{{ now(fmt='%Y%m%d%H%M%S') }}"
call_mode: "lookup('ansible.builtin.env', 'ANSIBLE_CALL_MODE', default='split')"
check_flag: "{{ download_root }}/to-notify-verifier-that-converged-in-check-mode"
ver2down: >-
  {{ lookup('ansible.builtin.env', 'ANSIBLE_DOWNLOAD_TAG', default='000') }}
download_tag: "v{{ ver2down }}"
download_root: "/tmp/molecule"
decompressed_file_name: "decompressed-file"
compression_formats:
  - [gz, bz2, lz4]
  - [zst, lzma, xz]
download_prefix: >-
  https://github.com/raven428/finch-externaleditor/releases/download/{{
    download_tag
  }}/pyenv2decompress-2_2_4-linux-amd64.tar
delegate_placeholder: "127.0.0.1" # DevSkim: ignore DS162092
meva_file2down: |
  {%  set result = [] %}
  {%  for format in compression_formats | flatten %}
  {%    do result.append({
          'url': download_prefix + '.' + format,
          'dest': download_root + '/local/' + format,
          'down_name': decompressed_file_name + '2local.' + format,
          'creates': decompressed_file_name,
          'delegate_to': delegate_placeholder,
          'archive': 'true',
          'files': [{
            'name': decompressed_file_name,
            'dest': format + '-local.tar',
            'file_mode': '0642',
          }]
        }) %}
  {%    do result.append({
          'url': download_prefix + '.' + format,
          'dest': download_root + '/remote/' + format,
          'down_name': decompressed_file_name + '2remote.' + format,
          'creates': decompressed_file_name,
          'archive': 'true',
          'down_mode': '0641',
          'modification_time': default_time,
        }) %}
  {%  endfor %}
  {{ result }}
